import { SLICE_NAME } from '@config/type';

export const GET_INFO = SLICE_NAME.ACCOUNT + 'GET_INFO';
export const GET_ALL_ACCOUNT = SLICE_NAME.ACCOUNT + 'GET_ALL_ACCOUNT';
export const SET_LIST_BANK = SLICE_NAME.ACCOUNT + 'SET_LIST_BANK';
export const GET_ALL_CARD = SLICE_NAME.ACCOUNT + 'GET_ALL_CARD';
export const SET_LIST_BEN_ACC = SLICE_NAME.ACCOUNT + 'SET_LIST_BEN_ACC';
export const SET_LIST_RECENT_BEN_ACC = SLICE_NAME.ACCOUNT + 'SET_LIST_RECENT_BEN_ACC';
export const CHECK_HAS_SMOTP = SLICE_NAME.ACCOUNT + 'CHECK_HAS_SMOTP';
export const GET_TRANSACTION_HISTORY = SLICE_NAME.ACCOUNT + 'GET_TRANSACTION_HISTORY';

export const GET_ACC_AVATAR = SLICE_NAME.ACCOUNT + 'GET_AVATAR';
