import { SLICE_NAME } from '@config/type';

export const LOGIN = SLICE_NAME.AUTHENTICATION + 'LOGIN';
export const LOGOUT = SLICE_NAME.AUTHENTICATION + 'LOGOUT';
export const CLEAR_SESSION = SLICE_NAME.AUTHENTICATION + 'CLEAR_SESSION';
export const RE_LOGIN = SLICE_NAME.AUTHENTICATION + 'RE_LOGIN';

// device
export const GET_DEVICES = SLICE_NAME.AUTHENTICATION + 'GET_DEVICES';
export const REMOVE_DEVICES = SLICE_NAME.AUTHENTICATION + 'REMOVE_DEVICES';
export const SET_DEVICES = SLICE_NAME.AUTHENTICATION + 'SET_DEVICES';

// onboard
export const SET_OB_TOKEN = SLICE_NAME.ONBOARD + 'SET_OB_TOKEN';
export const GET_OB_TOKEN = SLICE_NAME.ONBOARD + 'GET_OB_TOKEN';
export const REMOVE_OB_TOKEN = SLICE_NAME.ONBOARD + 'REMOVE_OB_TOKEN';
