import { SLICE_NAME } from '@config/type';

export const SYNC_CODE_PUSH = SLICE_NAME.OTHERS + 'SYNC_CODE_PUSH';
export const RESTART_APP = SLICE_NAME.OTHERS + 'RESTART_APP';
export const SHOW_ALERT = SLICE_NAME.OTHERS + 'SHOW_ALERT';
export const CHECK_UPDATE_CODE_PUSH = SLICE_NAME.OTHERS + 'CHECK_UPDATE_CODE_PUSH';
