import { SLICE_NAME } from '@config/type';

export const SET_LIST_BEN_ACC = SLICE_NAME.TRANSFER + 'SET_LIST_BEN_ACC';
export const GET_LIST_BANK = SLICE_NAME.TRANSFER + 'GET_LIST_BANK';
export const SET_LIST_RECENT_BEN_ACC = SLICE_NAME.TRANSFER + 'SET_LIST_RECENT_BEN_ACC';
