const eventConstant = {
  ON_QR_CODE: 'ON_QR_CODE',
  ON_SERVICE_PRESS: 'ON_SERVICE_PRESS',
  ON_RELOAD_LISTACCOUNT_SAVING: 'ON_RELOAD_LISTACCOUNT_SAVING',
  ON_RELOAD_GET_DETAIL: 'ON_RELOAD_GET_DETAIL',
  READ_ALL_NOTIFICATION_SUCCESS: 'READ_ALL_NOTIFICATION_SUCCESS',
  REMOVE_ALL_NOTIFICATION: 'REMOVE_ALL_NOTIFICATION',
  UNDO_ACTION_REMOVE_ALL_NOTIFICATION: 'UNDO_ACTION_REMOVE_ALL_NOTIFICATION',
  HAVE_NEW_NOTIFICATION: 'HAVE_NEW_NOTIFICATION',
  SET_TOTAL_NOTIFICATION_UNREAD: 'SET_TOTAL_NOTIFICATION_UNREAD',
  CLOSE_BIOMETRIC: 'CLOSE_BIOMETRIC',
};

export default eventConstant;
